# Generated by Django 4.2 on 2023-07-11 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('mail', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name_specialization', models.CharField(max_length=10)),
                ('name_university', models.CharField(max_length=15)),
                ('course', models.IntegerField(max_length=6)),
                ('ID_group', models.CharField(max_length=15)),
            ],
        ),
    ]
