# Generated by Django 4.2 on 2023-07-11 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0002_remove_group_id_alter_group_id_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
