# Generated by Django 4.2 on 2023-07-12 07:00

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0004_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=10)),
                ('ID_author', models.UUIDField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_proff', models.CharField(max_length=10)),
                ('ID_author', models.UUIDField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=9)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name_specialization', models.CharField(max_length=10)),
                ('name_university', models.CharField(max_length=35)),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2024)])),
                ('ID_user', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in_group', models.BooleanField(default=True)),
                ('moder', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человек(-а)',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='ID_users',
            field=models.UUIDField(default=10),
        ),
        migrations.AddField(
            model_name='group',
            name='name_users',
            field=models.CharField(default=10, max_length=55),
        ),
        migrations.AlterField(
            model_name='group',
            name='ID_group',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_specialization',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
