# Generated by Django 4.2 on 2023-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0005_data_feedback_user_group_id_users_group_name_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='ID_group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='ID_users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ID_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='name_group',
            field=models.CharField(default='БАГ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='group',
            name='name_user',
            field=models.CharField(default='БАГ', max_length=55),
        ),
        migrations.AddField(
            model_name='user',
            name='name_user',
            field=models.CharField(default='БАГ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='ID_author',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ID_author',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
