# Generated by Django 4.2 on 2023-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0006_remove_data_id_remove_feedback_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Человеки'},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='ID_author',
            new_name='name_user',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='ID_author',
            new_name='name_user',
        ),
        migrations.AddField(
            model_name='user',
            name='name_group',
            field=models.CharField(default='БАГ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.CharField(default='БАГ', max_length=15),
        ),
    ]
