# Generated by Django 4.2 on 2023-07-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0007_delete_group_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name_user',
            new_name='name_group',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name_user',
            new_name='name_group',
        ),
    ]
