# Generated by Django 4.2 on 2023-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0008_rename_name_user_data_name_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_group',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.CharField(max_length=15),
        ),
    ]
