# Generated by Django 4.2 on 2023-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0009_alter_user_name_group_alter_user_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_group',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.CharField(max_length=55),
        ),
    ]
