# Generated by Django 4.2 on 2023-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0012_alter_feedback_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lesson',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name_proff',
            field=models.CharField(max_length=20),
        ),
    ]
